services:

  postgres-db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    healthcheck:
      test: ["cmd", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
